### ISSUE TITLE
Not getting notifications from my Ring Doorbell Pro

### ISSUE THREAD

**Issue by AAMM007** [dgreif/ring#1107]
# Bug Report

### Describe the Bug
-Not getting notifications from my Ring Doorbell Pro (motion or by pressing the button)

### To Reproduce
-Press the Ring Doorbell Pro button or if a person move in front of the camera

### Expected behavior
-Receive notifications on my iPhone or/and Apple TV via HomeKit

### Screenshots/Logs
The notifications are turned on for this accessorily in HomeKit 

![IMG_1392](https://user-images.githubusercontent.com/106596626/202934839-0575c32b-abfb-4dcf-b78b-3a217a54ee9a.jpeg)

### Additional context
-I'm already using the plugin for my Alarm and everything works flawlessly, I just added the doorbell this week
-I can see perfectly the video stream of the doorbell camera in HomeKit
-I was wondering if this could be caused by the Smart Alert function in the Ring settings, it's turned on for person detection

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_

"refreshToken": "xxx",
            "hideDoorbellSwitch": true,
            "_bridge": {
                "username": "xxx",
                "port": 48808
            },
            "platform": "Ring"

### Environment

 - OS: Raspbian
 - Node.js: 18.12.1
 - NPM: 8.19.2
 - homebridge-ring: 11.6.0
 - homebridge: 1.5.1
 - hoobs: n/a

**Comment by jackklink** [comment]
I am also no longer receiving notifications or HomePod alerts for my doorbell. I have reset my network and devices and still have the issue

**Comment by jeph** [comment]
I'm still receiving notifications, however, I'm now experiencing a small delay (usually around 10-15 seconds) between when the doorbell is pressed and when I hear the chime on my HomePod. I haven't observed this previously although I haven't had my doorbell rang too frequently since I've set this up so this is also potentially not new behavior.

**Comment by satrik** [comment]
I updated to version 11.6.0 three days ago and since then I had the same behavior like described by jeph. in my case both, the chime on the HomePod and the HomeKit notifications were delayed. 

just tried to trace back the code and for my Doorbell 3 (battery powered) I found the issue. the code [here](https://github.com/dgreif/ring/blob/435e351f01ecd170254cff217168089b16ebbb85/packages/homebridge-ring/camera.ts#L218) says that my doorbell should only log `Doorbell Pressed` and immediately return the characteristic. but actual it logs `Doorbell Pressed. Loading snapshot before sending event to HomeKit` and then it waits for the snapshot before the characteristic gets returned. so it looks like the "ring-client-api" recognizes the power mode for my model wrong. if I use only this part of the function, it works again and there is no more delay.

```
private async loadSnapshotForEvent<T>(
    eventDescription: string,
    characteristicValue: T
  ) {
      logInfo(this.device.name + ' ' + eventDescription)
      return characteristicValue
}
```

maybe this findings can help to fix the issue :)

**Comment by dgreif** [comment]
@satrik thanks for tracking it back to the battery detection! That sounds like it could be related to #1109 and a few other issues recently reported with battery cameras. I'll dig into it!

**Comment by dgreif** [comment]
I've released `11.7.0-beta.3` which should fix the delayed notifications. @satrik @jeph would you mind trying it out to confirm?

@AAMM007 I'm not positive this will fix your notification issues as it sounds like you aren't receiving _any_ notifications, but give it a try and let me know if it helps

**Comment by jeph** [comment]
> I've released `11.7.0-beta.3` which should fix the delayed notifications. @satrik @jeph would you mind trying it out to confirm?

Just did some testing. Seems like your fix did the trick! Delay feels like it's half a second to a second now. I'll continue to pay attention to the delay for the next few days, but it seems to work as expected now. Thanks for the fix!

**Comment by AAMM007** [comment]
@dgreif I just tried the beta version, it still doesn’t work for me. No notifications at all for motion and doorbell button.

**Comment by marksthomas** [comment]
Just chiming in (sorry bad pun) to say I still have the 15 second delay before HomePod chimes on beta 3 too.

**Comment by chinedu40** [comment]
This appeared to fix my issue listed here https://github.com/dgreif/ring/issues/933#issuecomment-1315892273

**Comment by dgreif** [comment]
`11.7.0` has been released with a fix for the delays snapshots. @AAMM007 if that does not fix your issues, I'm afraid you are probably one of the few users for whom Push Notifications simply don't work properly. I have considered re-introducing polling as a workaround, but it adds a lot of complexity which I'm not sure I really want to add back to the project.

**Comment by marksthomas** [comment]
Resolved here. Thank you!

**Comment by AAMM007** [comment]
@dgreif Still nothing, I also added a Stick Up Cam (plug-in) and I'm also not getting any notifications.
Could the "Smart Alerts" feature create this issue, it's currently turned on?

![IMG_1466](https://user-images.githubusercontent.com/106596626/207070589-78007334-b47e-4c32-bce0-bae0b6a12a24.jpg)

**Comment by dgreif** [comment]
That's possible @AAMM007, I believe those settings will filter down what notifications get sent. Could you try turning those off and see if it starts working?

**Comment by theimo1221** [comment]
@dgreif For us over at ioBroker Ring the systemID was the reason of some users not getting the events, as ring seems to block certain (multi used) system id's.

**Comment by AAMM007** [comment]
@theimo1221 thanks for the info it works now. I just remove all authorized devices from my Ring account and generated a new token in my Homebridge Ring plugin.

@dgreif it also works with my Smart Alerts turned on

**Comment by dgreif** [comment]
Great, glad to hear it's working! Thanks for the pointer @theimo1221
