### ISSUE TITLE
Config validation failed

### ISSUE THREAD

**Issue by angushants** [dgreif/ring#1654]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe The Bug

I've not had any issues with previous versions, but with 14.0.1 it's failing to save my log in credentials for Ring, and reports that the "Config validation failed". As a consequence I can't add any Ring devices to Home at the moment 

### To Reproduce

Install 14.0.1; enter Ring username and password; enter code from Ring on SMS; click save - receive error message, no refresh token saved, no configs saved

### Expected behavior

Config saved and able to add devices

### Relevant log output

```shell
[07/09/2025, 21:45:29] [Tapo Smart Platform] 111 Error: connect ECONNRESET 192.168.1.179:80
[07/09/2025, 21:45:29] Homebridge v1.11.0 (HAP v0.13.1) (Homebridge 1483) is running on port 51242.
[07/09/2025, 21:45:29] [SamsungTizen] TV IP address is required for undefined
[07/09/2025, 21:45:29] [Tapo Smart Platform] Trying KLAP Auth
[07/09/2025, 21:45:29] Frame TV F8AF is running on port 40077.
[07/09/2025, 21:45:29] Please add [Frame TV F8AF] manually in Home app. Setup Code: 843-19-064
[07/09/2025, 21:45:29] [Tapo Smart Platform] 276 Error: connect ECONNRESET 192.168.1.179:80
[07/09/2025, 21:45:29] [Tapo Smart Platform] KLAP Handshake failed
[07/09/2025, 21:46:57] [Homebridge UI] [homebridge-ring] Incoming Request: /send-code
[07/09/2025, 21:46:57] [Homebridge UI] [homebridge-ring] Logging in with email 'angus.grant@salientprojects.co.uk'
[07/09/2025, 21:46:58] [Homebridge UI] [homebridge-ring] Please enter the code sent to +44xxxxxxxxxx via sms
[07/09/2025, 21:47:05] [Homebridge UI] [homebridge-ring] Incoming Request: /token
[07/09/2025, 21:47:05] [Homebridge UI] [homebridge-ring] Getting token for xxx.xxx@xxxx.co.uk with code 922647
[08/09/2025, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[08/09/2025, 01:41:15] [Homebridge UI] Running scheduled instance backup...
[08/09/2025, 01:41:15] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-qOmGxn/homebridge-backup-0E77392D1483.1757292075022.tar.gz.
[08/09/2025, 12:18:38] [Homebridge UI] [homebridge-ring] Incoming Request: /send-code
[08/09/2025, 12:18:38] [Homebridge UI] [homebridge-ring] Logging in with email 'xxx.xxx@xxxx.co.uk'
[08/09/2025, 12:18:39] [Homebridge UI] [homebridge-ring] Please enter the code sent to +44xxxxxxxxxx via sms
[08/09/2025, 12:18:52] [Homebridge UI] [homebridge-ring] Incoming Request: /token
[08/09/2025, 12:18:52] [Homebridge UI] [homebridge-ring] Getting token for xxx.xxx@xxxx.co.uk with code 624987
[08/09/2025, 12:28:24] [Homebridge UI] [homebridge-ring] Incoming Request: /send-code
[08/09/2025, 12:28:24] [Homebridge UI] [homebridge-ring] Logging in with email 'xxx.xxx@xxxx.co.uk'
[08/09/2025, 12:28:24] [Homebridge UI] [homebridge-ring] Please enter the code sent to +44xxxxxxxxxx via sms
[08/09/2025, 12:28:47] [Homebridge UI] [homebridge-ring] Incoming Request: /token
Getting token for xxx.xxx@xxxx.co.uk with code 635937
[08/09/2025, 12:29:54] [Homebridge UI] [homebridge-ring] node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:877:20)
    at target.send (node:internal/child_process:751:19)
    at PluginUiServer.ready (file:///var/lib/homebridge/node_modules/homebridge-ring/node_modules/@homebridge/plugin-ui-utils/dist/server.js:104:17)
    at new PluginUiServer (file:///var/lib/homebridge/node_modules/homebridge-ring/lib/homebridge-ui/server.js:11:14)
    at startPluginUiServer (file:///var/lib/homebridge/node_modules/homebridge-ring/lib/homebridge-ui/server.js:51:12)
    at file:///var/lib/homebridge/node_modules/homebridge-ring/lib/homebridge-ui/server.js:53:1
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:651:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
Emitted 'error' event on process instance at:
    at node:internal/child_process:881:39
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
```

### Homebridge Ring Config

```shell
OS	Debian GNU/Linux Bookworm (12)
Arch.	arm64 (64-bit)
IPv4 (eth0)	192.168.1.131
IPv6 (eth0)	fdba:4de6:b832:9649:fc47:67fe:9521:6989
Hostname	homebridge
User	pi
Node.js Path	/opt/homebridge/bin
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Time Zone	BST+0100
```

### OS

Raspian

### Node.js Version

v22.19.0

### NPM Version

v10.9.3

### Homebridge/HOOBs Version

v1.11.0

### Homebridge Ring Plugin Version

v14.0.1

### Operating System

Raspian

**Comment by vmcilwain** [comment]
I am experiencing this as well on Mac OS 13.5.1

When supplying my credentials, I see the refresh token flash in the text input. I save and get the message, no refresh token saved, no configs saved

OS

Mac OS 13.5.1

Node.js Version

v22.18.0

NPM Version

v10.9.3

Homebridge

v1.11.0

Homebridge Ring Plugin Version

v14.0.1

Operating System

Ventura

**Comment by angushants** [comment]
Still leaving it as a bug for now, but I was finally able to get the refresh token to stick and be saved - took about 6 or more goes of repeatedly logging into my Ring account.

**Comment by vmcilwain** [comment]
My issue is resolved as well. When I reported my issue, I was using Safari. I tried Safari a couple of more times today and had no luck. I decided to try using Chrome and it worked on the first try.

**Comment by dgreif** [comment]
I'm guessing this was a temporary issue with Rings API. Closing as I don't think it's actionable at the moment.

**Comment by bwtjr** [comment]
Still seeing this as a bug right now. I've tried ~10 times on both Safari and Chrome with no luck.

**Comment by gt9228a** [comment]
I also am seeing this - ive tried multiple different browsers without success.  The Token is briefly splashed on screen but cannot retrieve it.,

**Comment by bwtjr** [comment]
> I also am seeing this - ive tried multiple different browsers without success. The Token is briefly splashed on screen but cannot retrieve it.,

After around 20 tries, it finally stuck. I did do it in Chrome, but I have no idea if that helped or not because it had failed ~10 times on Chrome before it worked.

**Comment by gt9228a** [comment]
I was able to manually do it using the npx -p ring-client-api ring-auth-cli command in the terminal but never could get the UI to do it.

**Comment by dgreif** [comment]
Are y'all using the homebridge ui, or HOOBS?

**Comment by vmcilwain** [comment]
> Are y'all using the homebridge ui, or HOOBS?

I was/am using homebridge ui when my issue was happening.
