### ISSUE TITLE
Getting a bunch of errors since the Ring TypeScript API update

### ISSUE THREAD

**Issue by nackerr** [dgreif/ring#222]
Failed to prepare stream for Front Door (0.23s)
[1/11/2020, 12:55:08 AM] [Ring] TypeError: Cannot read property 'split' of undefined
    at new SipSession (/usr/lib/node_modules/homebridge-ring/lib/api/sip-session.js:103:23)
    at RingCamera.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:277:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by xxxchris** [comment]
same here

**Comment by dgreif** [comment]
Wow.  Just wow.  Sorry guys, Ring is so inconsistent between their wired cameras and battery cameras.  I changed around the way we fetch the connection info for live streaming and apparently this approach only works for wired cameras (which is all that I tested it with 🤦‍♂).  I should have a fix out this weekend if I get time, but you are welcome to revert to the previous version if you need live streams right away.  Sorry for the bug!

**Comment by xxxchris** [comment]
allready done. Please tell us when there is a fix. I appreciate your work. Thanks a lot and greetings from germany

**Comment by jeroenterheerdt** [comment]
same issue here - what is the fix?

**Comment by dgreif** [comment]
@jeroenterheerdt as I stated above, you can just use the old version for now.  I have the fix done, but was trying to get some additional improvements in for live streaming before my next release

**Comment by jeroenterheerdt** [comment]
@dgreif thanks - got it.

**Comment by nackerr** [comment]
@dgreif Thanks for the quick responses!

**Comment by dgreif** [comment]
Thanks for your patience everyone!  These errors should be gone in v`15.3.1`

**Comment by nackerr** [comment]
I seem to be getting another issue now.

**Comment by nackerr** [comment]
[1/16/2020, 1:38:33 AM] [Ring] Failed to prepare stream for Front Door (0.159s)
[1/16/2020, 1:38:33 AM] [Ring] TypeError: Cannot read property 'split' of undefined
    at new SipSession (/usr/lib/node_modules/homebridge-ring/lib/api/sip-session.js:103:23)
    at RingCamera.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:277:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by nackerr** [comment]
pi@raspberrypi:~ $ npm show homebridge-ring version
5.13.1


I'm up to date as well

**Comment by scotch115** [comment]
Same here, I'm also getting the 'TypeError: Cannot read property 'split' of undefined
at new SipSession...' error. Snapshots still work fine, but live stream fails.

v6.1.0

**Comment by dgreif** [comment]
@scotch115 that issue should be fixed in 6.1.0.  Have you tried restarting your homebridge server since you updated?

**Comment by scotch115** [comment]
Yeah, I've tried reverting to an older version, I've tried uninstalling and reinstalling the package, and rebooting my Pi--still getting 'Failed to prepare stream for Front Door.'

**Comment by dgreif** [comment]
Is it giving the `Cannot read property 'split' of undefined
at new SipSession.` error every time, or just failing to start live stream?  And did live streams work previously, or have you always had issue until updating?

**Comment by scotch115** [comment]
Live streams have never worked on my Raspberry Pi, but work fine when I run Homebridge on my Mac. I even flashed my Pi with a fresh install of Raspbian--no luck. The error I'm getting is:
```
[1/23/2020, 9:31:14 AM] [Ring] Failed to prepare stream for Front Door (0.305s)
[1/23/2020, 9:31:14 AM] [Ring] TypeError: Cannot read property 'split' of undefined
    at new SipSession (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-session.js:103:23)
    at RingCamera.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:277:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dgreif** [comment]
I'm sorry, but that's not the latest version of the code.  I'm not sure why it's not updating for you, but that `split` call is now in `sip-call.js` instead of `sip-session.js` (which is what your error show).  You may have the plugin installed multiple different ways on that computer (globally and in some specific folder), but you will have to track that down on your own.  Once you get it properly updated to the latest version, that error will go away.

**Comment by scotch115** [comment]
Okay, I'll try to uninstall globally and try it again. Thanks for the quick responses!

**Comment by scotch115** [comment]
Uninstalling globally fixed it--thanks!
