### ISSUE TITLE
Get locations fails with HTTP 404

### ISSUE THREAD

**Issue by wgbartley** [dgreif/ring#699]
# Bug Report

### Describe the Bug
Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404.

### To Reproduce
- Start/restart Homebridge
- View logs

### Expected behavior
Expected behavior would be no error reported

### Screenshots/Logs
```
[7/27/2021, 1:22:37 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
[7/27/2021, 1:22:37 PM] [Ring] Error connecting to API
[7/27/2021, 1:22:37 PM] [Ring] HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1627406557813,
    socket: 1627406557957,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: 1627406557957,
    response: 1627406557985,
    end: 1627406557985,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 144,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: NaN,
      firstByte: 28,
      download: 0,
      total: 172
    }
  }
}
```

### Additional context
I am also using ring-client-api in a separate script.  Ring.getCameras() also returns a 404.

### Homebridge Ring Config
```
    "platforms": [
        {
            "refreshToken": "xxx",
            "platform": "Ring"
        }
    ],
```

### Environment
 - OS: Running in oznu/homebridge docker container with Ubuntu 20.04.2 LTS host OS
 - Node.js: 14.17.1
 - NPM: 6.14.13
 - homebridge-ring: 9.18.5
 - homebridge: 1.3.4
 - hoobs: N/A

**Comment by stubbz00** [comment]
I'm getting this error as well.  I think it is on the Ring side as they are currently having outages for Video on Demand and Live Calls (Doorbell Dings & Motions).

**Comment by wgbartley** [comment]
You would think they would return something other than a 404 if there were server-side issues (like a 500-level error).

I'll keep an eye on https://status.ring.com to see when it clears up.  Hopefully the errors are related!

**Comment by x5nder** [comment]
Same errors here as well... tried reinstalling the plugin but now my Ring device has completely disappeared from Home. Hope it'll be fixed with a restart later tonight :x

**Comment by mpreissner** [comment]
I'm also having this issue.  Originally I thought it was a conflict between the Ring plugin and the homebridge-platform-insteonlocal I had installed (as the issue only appeared for me when I was configuring the Insteon plugin), but issue persists even after nuking my SD card and re-imaging from scratch with the official Homebridge Raspberry Pi image.

status.ring.com says everything is good now, but still seeing the errors.

Environment
OS: Raspbian GNU/Linux 10 (buster)
Node.js: 14.17.3
NPM: 6.14.13
homebridge-ring: 9.18.5
homebridge: 1.3.4
hoobs: N/A

**Comment by stubbz00** [comment]
Yep.  Still getting error as well even after restarting the child bridge I have for ring.

Environment
OS: Debian/DietPi 7.4
Node.js: 14.17.2
Npm: 7.20.0
homebridge-ring: 9.18.5
homebridge: 1.3.4

**Comment by wgbartley** [comment]
https://status.ring.com is reporting that all issues are resolved.  Still getting HTTP 404 errors after restarting Homebridge and re-running my script that uses the ring-client-api library.

**Comment by Schosch83** [comment]
Same error here.
After Update Node from v14.17.0 to 14.17.3.
Npm: v 6.14.13
I try to go back v14.17.0 but the Same error.

**Comment by pmaspero** [comment]
same error here, tried to downgrade Ring, still getting the same error

**Comment by rpmartinez3** [comment]
Same here

**Comment by wgbartley** [comment]
It looks like PR https://github.com/dgreif/ring/pull/708 fixed it with the new location.  I've updated the plugin in Homebridge as well as the NPM package in my standalone script and both are working now.  Many thanks to @mkellsy and @dgreif!

**Comment by raleighlittles** [comment]
I'm still having this issue. The ring.com website is still functioning as is so I don't think it's an issue on that end.
